name: Release GitHub Page

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install packages
        run: npm install
      - name: build blog
        run: npm run build
      - name: export blog
        run: npm run export

      # 生成した結果を保存しておく
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: export_out
          path: ./out

      # gh-pagesを使って公開(private key: SSH_KEY)
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        #env:
        with:
          deploy_key: ${{ secrets.SSH_KEY }} # 鍵の名前を指定
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./out
          cname: cardseditor.gajeroll.com #カスタムドメインを指定

      - name: push with rsync
        run: rsync -rlptgoD -O --delete --exclude ".git/" -e "ssh -i .ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" dist/ $SSH_USER@$SSH_HOST:$DIR
        env:
          DIR: ~/public_html/hoge
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
