name: deploy to ConoHa WING

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: install
        - uses: borales/actions-yarn@v2.3.0
          with:
            cmd: build
        - name: ssh key generate
          run: echo "$SSH_KEY" > key && chmod 600 key
          env:
            SSH_KEY: ${{ secrets.SSH_KEY }}
        - name: rsync deployments
          uses: burnett01/rsync-deployments@5.1
          with:
            switches: -avz --delete
            path: pages/
            remote_path: ${{ secrets.SSH_PATH }}
            remote_host: ${{ secrets.SSH_HOST }}
            remote_user: ${{ secrets.SSH_USER }}
            remote_port: ${{ secrets.SSH_PORT }}
            remote_key: ${{ secrets.SSH_KEY }}